edoc/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_jwt.views import obtain_jwt_token

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = "E-Doctor System"
admin.site.index_title = 'E-Doctor Site Administration'

urlpatterns = [
    path('', admin.site.urls),
    # path('', include('users.urls')),
    # path('visitor/',include('visitor.urls', namespace="visitor")),
    path('users/', include('django.contrib.auth.urls')),
    # path('patient/',include('patient.urls', namespace="patient")),
    # path('pathologist/',include('Lab_Pathologist.urls', namespace="pathologist")),
    # path('doctor/',include('doctor.urls', namespace="doctor")),
    path('api/auth/token/', obtain_jwt_token),
    path('api/users/', include(("users.api.urls",'users-api'), namespace='users-api')),
    path('api/doctors/', include(("doctor.api.urls",'doctor-api'), namespace='doctor-api')),
    path('api/nurses/', include(("nurse.api.urls",'nurse-api'), namespace='nurse-api')),
    path('api/patients/', include(("patient.api.urls",'patient-api'), namespace='patient-api')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (register_patient, home_page, registration_redirect, redirect_logged, dashboard, about, contact)

app_name = 'users'
urlpatterns = [
        path('login/', auth_views.LoginView.as_view(), name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),
        path('password-reset/',auth_views.PasswordResetView.as_view(template_name='reset/password_reset_form.html'),name='password_reset'),
        path('users/password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='reset/password_reset_done.html'),name='password_reset_done'),
        path('users/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='reset/password_reset_confirm.html'),name='password_reset_confirm'),
        path('users/reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='reset/password_reset_complete.html'),name='password_reset_complete'),
        path('dash/',redirect_logged, name='dash'),
        path('admin/',  dashboard , name='dashboard'), 
        path('register/patient/', register_patient, name='register_patient'),
        path('register/', registration_redirect , name='registration_redirect'),
        path('aboutus/', about, name='about'),
        path('contact/', contact, name='contact'),
        path('', home_page, name='home_page'),
]

templates/about_template.html
 {% load static %}
<h2 style="color: #2196f3;margin-top: 2%; text-align: center;">About Us</h2>

<!-- contact -->
<section class="contact-w3pvt py-lg-5">
    <div class="container py-md-5">
        <div>

            <!-- <img src="{% static 'images/logo/prueleo_logo1.png' %}" class="img img-responsive" style="margin: auto;" align="center"><br> -->
        </div>
        <p>Medical Laboratories was established in October 1985. The laboratory became the first ISO 15189 Accredited private laboratory in Zimbabwe in July 2014. CIMAS acquired the assets and staff of the Medical Laboratories in October 1985 in order to
            ensure that private laboratory services would continue to be available for the medical profession and the public of Zimbabwe. The decision to take over the laboratories was made when the pathologists who owned the Laboratories decided to retire.
            In 1988 CIMAS also acquired the assets and staff of the Bulawayo Laboratory. These were combined as CIMAS Medical Laboratories and formed the basis of the Society's Medical Services Division.</p>
    </div>
    <!-- <a href="{% url 'users:contact' %}">Login</a> -->
    <a href="contact_template.html">Login Hey</a>
</section>
<!-- //contact -->

templates/contact_template.html
<h2 style="color: #2196f3;margin-top: 2%; text-align: center;">Contact Us</h2>

{% comment %}
<div class="inner-banner-w3ls">
</div> {% endcomment %}
<!-- breadcrumbs -->
<!--<nav aria-label="breadcrumb">
        <ol class="breadcrumb d-flex justify-content-center bg-theme">
            <li class="breadcrumb-item">
                <a href="index.html" class="text-white">Home</a>
            </li>
            <li class="breadcrumb-item active text-white font-weight-bold" aria-current="page">Contact Us</li>
        </ol>
    </nav>-->
<!-- //breadcrumbs -->
<!-- contact -->
<section class="contact-w3pvt py-lg-5">
    <div class="container py-md-5">
        <div class="address-w3layouts">
            <div class="title-sec-w3layouts_pvt text-center" style="margin-bottom: 5%;">
                <span class="title-wthree">a world full of possibilities</span>
                <h4 class="w3layouts_pvt-head">our contact info</h4>
            </div>
            <div class="row py-md-5 pt-4">
                <div class="col-lg-4">
                    <div class="row fv3-contact">
                        <div class="col-4  text-center">
                            <span class="fa fa-envelope-open ml-2"></span>
                        </div>
                        <div class="col-8">
                            <a href="mailto:cimasmedlabs@email.com" class="d-block text-secondary">cimasmedlabs@gmail.com</a>
                            <a href="mailto:admin@cimasmedlabs.com" class="d-block text-secondary">admin@cimasmedlabs.com</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 my-lg-0 my-4">
                    <div class="row  fv3-contact">
                        <div class="col-4 my-2 text-center">
                            <span class="fa fa-phone ml-2"></span>
                        </div>
                        <div class="col-8">
                            <p>+263 775 078 468</p>
                            <p>+263 718 681 493</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="row fv3-contact">
                        <div class="col-4  text-center">
                            <span class="fa fa-home ml-2"></span>
                        </div>
                        <div class="col-8">
                            <p>Cimas MedLabs , 42 Sam Nujoma ,Corner 2nd Street
                                <br>Harare , Zimbabwe.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12 mx-auto">
                <!-- register form grid -->
                <div class="register-top1 py-lg-3">
                    <div class="title-sec-w3layouts_pvt text-center">
                        <h4 class="w3layouts_pvt-head">How Can We Help You?</h4>
                    </div>
                    <form action="#" method="get" class="register-wthree pt-md-5 pb-md-0 py-4">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>
                                            First name
                                        </label>
                                    <input class="form-control" type="text" placeholder="Johnson" name="email" required="">
                                </div>
                                <div class="col-md-6 mt-md-0 mt-4">
                                    <label>
                                            Last name
                                        </label>
                                    <input class="form-control" type="text" placeholder="Kc" name="name" required="">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label>
                                            Mobile
                                        </label>
                                    <input class="form-control" type="text" placeholder="xxxx xxxxx" name="email" required="">
                                </div>
                                <div class="col-md-6 mt-md-0 mt-4">
                                    <label>
                                            Email
                                        </label>
                                    <input class="form-control" type="email" placeholder="example@email.com" name="email" required="">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12">
                                    <label>
                                            Your message
                                        </label>
                                    <textarea placeholder="Type your message here" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-agile btn-block w-100 font-weight-bold text-uppercase bg-theme">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
                <!--  //register form grid ends here -->
                <div class="border-pos-wthree border-exp"></div>
            </div>
        </div>
    </div>
</section>
<!-- //contact -->